## Spring related settings for dev profile ##

# Enable and use h2 console with the default path /h2-console
spring:
  h2:
    console:
      enabled: true
  # In development mode the app will store the database in memory with the default username and password
  datasource:
    url: jdbc:h2:mem:~/${spring.application.name}-dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password: pass1234!
    driver-class-name: org.h2.Driver
server:
  port: 8080